management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 12345

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-provider
          uri: lb://service1
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:33333
logging:
  level:
    root: info