server:
  port: ${port:56040} #启动端口 命令行注入
spring:
  application:
    name: service2
  main:
    allow-bean-definition-overriding: true # Spring Boot 2.1 需要设定
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: ${dubbo_port:-1}
  registry:
    address: nacos://127.0.0.1:8848
  application:
    qos-enable: false
  consumer:
    check: false